#!/usr/bin/env bash

cat <<EOF
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-app-tests
  namespace: default
spec:
  interval: 1m
  url: https://github.com/giantswarm/flux-app-tests
  secretRef:
    name: tests-github-credentials
  ref:
    branch: feature/init-with-data
  ignore: |
    tests/test_cases/**/result
---
EOF

generate_kustomization() {
    cat <<EOF
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test-$1
  namespace: default
spec:
  serviceAccountName: automation
  prune: true
  interval: 1m
  path: "./tests/test_cases/$1"
  sourceRef:
    kind: GitRepository
    name: flux-app-tests
  timeout: 2m
---
EOF
}

generate_all_tests() {
    for dir in $(dirname $0)/test_cases/*/
    do
      generate_kustomization $(basename $dir)
    done
}

if [ -z "$1" ]
then
    generate_all_tests
else
    generate_kustomization $1
fi
