apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: hello-world
  labels:
    app-operator.giantswarm.io/version: 0.0.0
spec:
  catalog: giantswarm
  kubeConfig:
    inCluster: false
  name: hello-world-app
